// <auto-generated />
using System;
using CMS.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240510200420_SeedMembersTable")]
    partial class SeedMembersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMS.Models.Models.Members", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MemberSince")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Membertbl");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "466 dummy address",
                            Email = "dummy@gmail.com",
                            FirstName = "John",
                            LastName = "Bob",
                            MemberSince = new DateTime(2024, 5, 10, 14, 4, 19, 858, DateTimeKind.Local).AddTicks(8339),
                            Phone = "555-888-666"
                        },
                        new
                        {
                            Id = 2,
                            Address = "466 dummy address",
                            Email = "dummy2@gmail.com",
                            FirstName = "James",
                            LastName = "Rob",
                            MemberSince = new DateTime(2024, 5, 10, 14, 4, 19, 858, DateTimeKind.Local).AddTicks(8394),
                            Phone = "555-888-888"
                        },
                        new
                        {
                            Id = 3,
                            Address = "466 dummy address",
                            Email = "dummy3@gmail.com",
                            FirstName = "Jacob",
                            LastName = "Job",
                            MemberSince = new DateTime(2024, 5, 10, 14, 4, 19, 858, DateTimeKind.Local).AddTicks(8396),
                            Phone = "555-888-777"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
