// <auto-generated />
using CMS.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMS.Models.Models.Members", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberSince")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Membertbl");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "466 dummy address",
                            Email = "dummy@gmail.com",
                            FirstName = "John",
                            LastName = "Bob",
                            MemberSince = "11/05/2024",
                            Phone = "555-888-666"
                        },
                        new
                        {
                            Id = 2,
                            Address = "466 dummy address",
                            Email = "dummy2@gmail.com",
                            FirstName = "James",
                            LastName = "Rob",
                            MemberSince = "11/05/2024",
                            Phone = "555-888-888"
                        },
                        new
                        {
                            Id = 3,
                            Address = "466 dummy address",
                            Email = "dummy3@gmail.com",
                            FirstName = "Jacob",
                            LastName = "Job",
                            MemberSince = "11/05/2024",
                            Phone = "555-888-777"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
